name: Deploy

on:
  workflow_run:
    workflows: [Build]
    types:
      - completed

jobs:
  deploy_live_website:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download pages
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}
          name: page-build
          path: public

      - name: change URLs for large files
        shell: bash
        run: |
          sed -i 's|search/search_index.json|https://storage.googleapis.com/cp-algorithms/search_index.json|g' public/assets/javascripts/*.js

      - id: 'auth'
        uses: 'google-github-actions/auth@v2.1.6'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: 'public/search/search_index.json'
          destination: 'cp-algorithms'

      - uses: FirebaseExtended/action-hosting-deploy@v0
        id: firebase-deploy
        with:
          repoToken: ${{ github.token }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: cp-algorithms
          channelId: live

  deploy_github_pages:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download pages
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}
          name: page-build
          path: public

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get PR information
        uses: potiuk/get-workflow-origin@v1_6
        id: source-run-info
        with:
          token: ${{ github.token }}
          sourceRunId: ${{ github.event.workflow_run.id }}

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.token }}
          publish_dir: ./public
          publish_branch: gh-pages
          destination_dir: ${{ steps.source-run-info.outputs.pullRequestNumber || 'main' }}/
    
      - name: Create or update PR comment
        if: steps.source-run-info.outputs.pullRequestNumber
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ steps.source-run-info.outputs.pullRequestNumber }}
          body: |
            Preview the changes for PR #${{ steps.source-run-info.outputs.pullRequestNumber }} (${{ github.event.workflow_run.head_sha }}) here: https://gh.cp-algorithms.com/${{ steps.source-run-info.outputs.pullRequestNumber }}/
          body-includes: 'Preview the changes for PR'
          mode: replace
