name: Deploy

on:
  workflow_run:
    workflows: [Build]
    types:
      - completed

jobs:
  deploy_github_pages:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Attach run to the commit
        uses: ./.github/actions/set-commit-status
        with:
          sha: ${{ github.event.workflow_run.head_sha }}
          status: pending

      - name: Download pages
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}
          path: public

      - name: Get PR number from artifact
        id: get-pr-number
        run: echo "pr_number=$(ls public)" >> $GITHUB_OUTPUT

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ github.token }}
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
          publish_dir: public/${{ steps.get-pr-number.outputs.pr_number }}
          destination_dir: ${{ steps.get-pr-number.outputs.pr_number }}
          full_commit_message: "Preview for ${{ steps.get-pr-number.outputs.pr_number != 'main' && '#' || '' }}${{ steps.get-pr-number.outputs.pr_number }} (${{ github.event.workflow_run.head_sha }}) at https://cp-algorithm.sideco.ir/pr/${{ steps.get-pr-number.outputs.pr_number }}/"

      - name: Set final commit status
        uses: ./.github/actions/set-commit-status
        if: always()
        with:
          sha: ${{ github.event.workflow_run.head_sha }}
